version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/smart_cart_db
      ELASTICSEARCH_PORT: 9200
      ELASTICSEARCH_HOST: elasticsearch
    depends_on:
      - db
      - elasticsearch
    entrypoint: bash -c "sleep 20 && alembic upgrade head && python app/seeders/Seed.py && python app/elasticsearch/es_index.py && uvicorn main:app --host 0.0.0.0 --port 8080"

  db:
    image: postgres:14.10-alpine3.18
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: smart_cart_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.name=es
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es
      - MAX_LOCKED_MEMORY=unlimited
    volumes:
      - ./es_data_volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  postgres_data:
