name: Lint Code

on:
  pull_request:
    paths:
      - '**/*.py'

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flake8
        id: lint
        run: |
          lint_results=$(flake8 --exit-zero)
          echo "lint_results=${lint_results}" >> $GITHUB_ENV


      - name: Post Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const lintResults = `${process.env.lint_results || ''}`;
            
            const commentBody = `
              **Linting Results:**
              ${lintResults}
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody,
            });
